steps:
  - uses: actions/checkout@v4

  - uses: actions/setup-python@v5
    with: { python-version: '3.x' }

  - run: pip install matrix-commander==8.*

  - name: archive matrix rooms
    env:
      MATRIX_HS:   ${{ secrets.MATRIX_HS }}
      MATRIX_USER: ${{ secrets.MATRIX_USER }}
      MATRIX_TOKEN:${{ secrets.MATRIX_TOKEN }}
      MATRIX_ROOMS:${{ secrets.MATRIX_ROOMS }}   # “roomA roomB #alias”
      LISTEN_MODE: all
      TIMEOUT:     15
    run: python scripts/update.py

  - name: commit artefacts
    run: |
      git config user.name  github-actions
      git config user.email gh-actions@users.noreply.github.com
      git add -A archive
      git diff --cached --quiet || \
        git commit -m "bot: archive update $(date -u +'%F')" && git push

  # ------- deploy to GitHub Pages (unchanged) ---------
  - name: upload pages
    uses: actions/upload-pages-artifact@v3
    with: { path: archive }        # serve the archive folder

  - uses: actions/deploy-pages@v4

